FROM nginx

COPY ./dist /usr/share/nginx/html

# RUN apt-get update
# RUN apt-get install vim lsof ping 

VOLUME [ "/usr/share/nginx/html" ]

EXPOSE 80

# docker build -f ./DockerFile  -t cricket-nginx:1.0 .

# docker run --name cricket-nginx -p 80:80 -itd --net cricket-net cricket-nginx:1.0